# Generated by Django 3.1.5 on 2021-02-01 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0004_auto_20210201_1826'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='title_ru',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='pokemon',
            old_name='title_eng',
            new_name='title_en',
        ),
    ]
